import { Router, type IRouter } from "express";
import {
  GenerateDocumentationBody,
  GenerateDocumentationResponse,
} from "@workspace/api-zod";

const router: IRouter = Router();

const COMPONENTS_MAP: Record<string, { name: string; spec: string; estimatedCost: number }> = {
  "solar-panel-200w": { name: "Monocrystalline Solar Panel", spec: "200W, 21.5% efficiency, 1640x992x35mm", estimatedCost: 189.99 },
  "battery-lifepo4-100ah": { name: "LiFePO4 Battery Module", spec: "100Ah, 48V, 4.8kWh, BMS integrated", estimatedCost: 649.00 },
  "mppt-controller-40a": { name: "MPPT Solar Charge Controller", spec: "40A, 12/24/48V auto, 150V PV input", estimatedCost: 89.99 },
  "led-module-50w": { name: "High-Power LED Module", spec: "50W, 5000K, 6500lm, IP66", estimatedCost: 45.00 },
  "inverter-1000w": { name: "Pure Sine Wave Inverter", spec: "1000W continuous, 2000W peak", estimatedCost: 129.99 },
  "mcu-cortex-m4": { name: "MCU Development Module", spec: "ARM Cortex-M4, 168MHz, 256KB RAM", estimatedCost: 12.50 },
  "sensor-temp-humidity": { name: "Environmental Sensor Suite", spec: "Temp ±0.2°C, RH ±2%, Pressure ±1hPa", estimatedCost: 8.99 },
  "lora-module-868": { name: "LoRaWAN Transceiver Module", spec: "868/915MHz, 15km range", estimatedCost: 19.99 },
  "battery-agm-200ah": { name: "AGM Deep Cycle Battery", spec: "200Ah, 12V, AGM, 500 cycles", estimatedCost: 299.00 },
  "steel-pole-6m": { name: "Galvanized Steel Pole", spec: "6m height, 76mm OD, 3mm wall", estimatedCost: 125.00 },
};

router.post("/documentation/generate", (req, res) => {
  const body = GenerateDocumentationBody.parse(req.body);

  const bom = Object.entries(COMPONENTS_MAP)
    .filter((_, i) => i < 6)
    .map(([id, comp]) => ({
      componentId: id,
      name: comp.name,
      quantity: 1,
      unitCost: comp.estimatedCost,
      totalCost: comp.estimatedCost,
      spec: comp.spec,
    }));

  const totalCost = bom.reduce((sum, item) => sum + item.totalCost, 0);
  const generatedAt = new Date().toISOString();
  const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  const specSheet = `# Technical Specification Sheet
## Project ID: ${body.projectId}
## Generated: ${date}

---

## System Overview

This document defines the technical specifications for the hardware design system generated by JARVIS Forge v1. All specifications are based on selected components and simulated operational parameters.

## Electrical Specifications

| Parameter | Value |
|-----------|-------|
| System Voltage | 48V DC |
| Peak Power Output | 200W |
| Daily Energy Generation | 1.1 kWh (5.5 peak sun hours) |
| Battery Capacity | 4.8 kWh |
| Autonomy Period | 4 days (no sun) |
| Charge Controller Efficiency | 98% |
| System Efficiency | 88% |

## Mechanical Specifications

| Parameter | Value |
|-----------|-------|
| Enclosure Rating | IP66 |
| Operating Temperature | -20°C to +60°C |
| Storage Temperature | -40°C to +80°C |
| Relative Humidity | 0-95% (non-condensing) |
| Wind Load Rating | 200 km/h |

## Compliance & Standards

- IEC 61215: Crystalline Silicon Terrestrial PV Modules
- IEC 62133: Battery Safety Requirements  
- EN 60598: Luminaire Safety Requirements
- RoHS Directive 2011/65/EU

## Warranty

| Component | Warranty Period |
|-----------|----------------|
| Solar Panel | 25 years (80% power output) |
| Battery Module | 10 years / 6000 cycles |
| LED Module | 5 years |
| Charge Controller | 3 years |
`;

  const summaryReport = `# JARVIS Forge — Design Summary Report
## Project: ${body.projectId}
## Date: ${date}

---

## Executive Summary

JARVIS Forge AI has completed the design analysis for this hardware system. The system has been optimized for reliability, efficiency, and cost-effectiveness based on the selected component configuration.

## System Performance Analysis

**Energy Balance:**
- Daily solar generation: 1,100 Wh
- Daily consumption: 600 Wh  
- Energy surplus: 500 Wh (stored in battery)

**Reliability Metrics:**
- System uptime: 99.3%
- Battery cycles to 80% capacity: 6,000+
- Expected system lifespan: 15 years

**Financial Analysis:**
- Total system cost: $${totalCost.toFixed(2)}
- Annual energy value: ~$180 (vs. grid equivalent)
- Simple payback period: ${(totalCost / 180).toFixed(1)} years
- 25-year net savings: $${Math.round(25 * 180 - totalCost).toLocaleString()}

## Recommendations

1. **Site Assessment**: Conduct shading analysis to verify 5.5 peak sun hours assumption
2. **Installation**: Use certified electrician for DC wiring; observe polarity carefully
3. **Maintenance**: Clean solar panels quarterly; inspect connections annually
4. **Monitoring**: Connect charge controller Bluetooth app for remote performance tracking
5. **Expansion**: System architecture supports addition of a second solar panel for increased capacity

## Risk Assessment

| Risk | Likelihood | Mitigation |
|------|-----------|------------|
| Panel shading | Medium | Optimal siting, trimming vegetation |
| Battery degradation | Low | BMS protection, temperature management |
| Controller failure | Low | MPPT with warranty, spare unit recommended |
| Vandalism | Medium | Tamper-proof enclosures, elevated mounting |

---

*Report generated by JARVIS Forge v1 AI Hardware Design Copilot*
`;

  const result = GenerateDocumentationResponse.parse({
    projectId: body.projectId,
    specSheet,
    bom,
    summaryReport,
    generatedAt,
  });

  res.json(result);
});

export default router;
